networks:
  default: localnet

  localnet:
    url: "http://127.0.0.1:4000/api"
    leader_only: false

  studio_devnet:
    url: "https://studio-dev.genlayer.com/api"

paths:
  contracts: "contracts"
  artifacts: "artifacts"
